SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
POWERUP_RADIUS = 10
POWERUP_SPAWN_RATE_SECONDS = 5
POWERUP_DURARTION_SECONDS = 1
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

FONT = "assets/fonts/DepartureMono-Regular.otf" 
SCORE_FONT_SIZE = 25 
SCORE_COORDINATES = (0,0)

BUTTON_FONT_SIZE = 30
FONT_COLOUR = "#FFFFFF"
BACKGROUND_COLOUR = "#000000"

PLAYER_TEXT_FONT_SIZE = 20
PROMPT_TEXT_FONT_SIZE = 25
SCORE_PROMPT_FONT_SIZE = 10
